### ISSUE TITLE
about RandomCrop

### ISSUE THREAD

**Issue by babyta** [skuley/DIS-Multi-Gpus-Training#2]
Hello, great work, I would like to ask, after the training mask is randomly cropped, how to ensure that it is consistent with the original image?

**Comment by skuley** [comment]
Hello @babyta 

I am afraid that i didn't fully understand your question.
Why would you want randomly cropped train dataset to be consistent to original image?

If I understood correctly, 
you randomly crop train image by p-value(with probability), thus original image can used too without any random crop.

Hope this answered your question
